[package]
entrypoint = "start"

[dependencies]
"python/python" = "3.13.1"
"wasmer/bash" = "=1.0.24"

[fs]
"/app" = "."
"/opt/venv/lib/python3.13/site-packages" = "/Users/syrusakbary/Development/langflow/src/backend/base/wasix-site-packages"

[[command]]
name = "start"
module = "python/python:python"
runner = "wasi"

[command.annotations.wasi]
cwd = "/app"
main-args = ["-c", "from langflow import __main__; __main__.main()"]
env = ["PYTHONEXECUTABLE=/bin/python", "PYTHONHOME=/cpython", "PYTHONPATH=/opt/venv/lib/python3.13/site-packages", "HOME=/app"]
