[package]
entrypoint = "start"

[dependencies]
"zebreus/python-with-libs" = "=0.1.2"
"wasmer/bash" = "=1.0.24"

[fs]
"/app" = "."
"/opt/venv/lib/python3.13/site-packages" = "./wasix-site-packages"

[[command]]
name = "start"
module = "zebreus/python-with-libs:python"
runner = "wasi"

[command.annotations.wasi]
cwd = "/app"
# main-args = ["-c", "from langflow import __main__; __main__.main()"]
main-args = [
    "-c",
    "from langflow import __main__; import sys; sys.argv = ['langflow', 'run', '--log-level', 'debug', '--host', '127.0.0.1', '--port', '9876', '--backend-only']; __main__.main()",
    # "import os; print(os.listdir('/app/langflow/frontend'))",
]
env = [
    "PYTHONEXECUTABLE=/bin/python",
    "PYTHONHOME=/cpython",
    "PYTHONPATH=/opt/venv/lib/python3.13/site-packages",
    "HOME=/app",
]
